// Generated by ReScript, PLEASE EDIT WITH CARE


var Null = {};

var Context = {};

var Canvas = {
  Context: Context
};

var $$Event = {};

export {
  Null ,
  Canvas ,
  $$Event ,
}
/* No side effect */
