// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Food from "./Food.bs.mjs";
import * as Snake from "./Snake.bs.mjs";
import * as Settings from "./Settings.bs.mjs";

function make(canvas) {
  return {
          context: canvas.getContext("2d"),
          width: canvas.width,
          height: canvas.height
        };
}

function getWidth(board) {
  return board.width;
}

function getHeight(board) {
  return board.height;
}

function clear(board) {
  board.context.clearRect(0, 0, board.width, board.height);
}

function drawFood(board, food) {
  var context = board.context;
  var rectSize = Settings.grid - 1 | 0;
  context.fillStyle = Settings.foodColor;
  context.fillRect(Food.getX(food), Food.getY(food), rectSize, rectSize);
}

function drawSnake(board, snake) {
  var context = board.context;
  var rectSize = Settings.grid - 1 | 0;
  context.fillStyle = Settings.snakeColor;
  Snake.iterateCells(snake, (function (x, y) {
          context.fillRect(x, y, rectSize, rectSize);
        }));
}

var Canvas;

export {
  Canvas ,
  make ,
  getWidth ,
  getHeight ,
  clear ,
  drawFood ,
  drawSnake ,
}
/* No side effect */
