// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Snake from "./Snake.bs.mjs";

function makeControl(snakeRef) {
  return function () {
    document.addEventListener("keydown", (function ($$event) {
            var snake = snakeRef.contents;
            var data_0 = $$event.which;
            var data_1 = Snake.getDx(snake);
            var data_2 = Snake.getDy(snake);
            switch (data_0) {
              case 37 :
                  if (data_1 !== 0) {
                    return ;
                  } else {
                    snakeRef.contents = Snake.setSpeedLeft(snake);
                    return ;
                  }
              case 38 :
                  if (data_2 !== 0) {
                    return ;
                  } else {
                    snakeRef.contents = Snake.setSpeedUp(snake);
                    return ;
                  }
              case 39 :
                  if (data_1 !== 0) {
                    return ;
                  } else {
                    snakeRef.contents = Snake.setSpeedRight(snake);
                    return ;
                  }
              case 40 :
                  if (data_2 !== 0) {
                    return ;
                  } else {
                    snakeRef.contents = Snake.setSpeedDown(snake);
                    return ;
                  }
              
            }
          }));
  };
}

export {
  makeControl ,
}
/* No side effect */
