// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Util from "./Util.bs.mjs";
import * as Settings from "./Settings.bs.mjs";

function make() {
  return {
          x: Math.imul(Util.getRandomInt(0, 25), Settings.grid),
          y: Math.imul(Util.getRandomInt(0, 25), Settings.grid)
        };
}

function getX(food) {
  return food.x;
}

function getY(food) {
  return food.y;
}

export {
  make ,
  getX ,
  getY ,
}
/* No side effect */
