// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Food from "./Food.bs.mjs";
import * as Board from "./Board.bs.mjs";
import * as Snake from "./Snake.bs.mjs";
import * as Settings from "./Settings.bs.mjs";

function make(board, snakeRef, foodRef) {
  var countRef = {
    contents: 0
  };
  var loop = function () {
    window.requestAnimationFrame(loop);
    var count = countRef.contents;
    var snake = snakeRef.contents;
    var food = foodRef.contents;
    if (count < Settings.countPerUpdate) {
      countRef.contents = count + 1 | 0;
      return ;
    } else {
      countRef.contents = 0;
      snakeRef.contents = Snake.move(snake, Board.getWidth(board), Board.getHeight(board));
      if (Snake.eatFood(snake, food)) {
        snakeRef.contents = Snake.increaseMaxCells(snake);
        foodRef.contents = Food.make(undefined);
      } else if (Snake.eatSelf(snake)) {
        snakeRef.contents = Snake.make(undefined);
        foodRef.contents = Food.make(undefined);
      }
      Board.clear(board);
      Board.drawFood(board, food);
      return Board.drawSnake(board, snake);
    }
  };
  return loop;
}

export {
  make ,
}
/* No side effect */
