// Generated by ReScript, PLEASE EDIT WITH CARE


var grid = 16;

var countPerUpdate = 16;

var boardId = "game-board";

var foodColor = "#F0DB4F";

var snakeColor = "#C3373D";

export {
  grid ,
  countPerUpdate ,
  boardId ,
  foodColor ,
  snakeColor ,
}
/* No side effect */
