// Generated by ReScript, PLEASE EDIT WITH CARE


function getRandomInt(min, max) {
  var diff = max - min;
  return Math.floor(Math.random() * diff) + min | 0;
}

export {
  getRandomInt ,
}
/* No side effect */
