// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Food from "./core/Food.bs.mjs";
import * as Game from "./core/Game.bs.mjs";
import * as Board from "./core/Board.bs.mjs";
import * as Snake from "./core/Snake.bs.mjs";
import * as Control from "./core/Control.bs.mjs";
import * as Settings from "./core/Settings.bs.mjs";

var snakeRef = {
  contents: Snake.make(undefined)
};

var foodRef = {
  contents: Food.make(undefined)
};

var canvas = document.getElementById(Settings.boardId);

if (canvas === null) {
  console.log("Cannot find element with id " + Settings.boardId);
} else {
  var board = Board.make(canvas);
  var loop = Game.make(board, snakeRef, foodRef);
  var registerControls = Control.makeControl(snakeRef);
  registerControls(undefined);
  loop(undefined);
}

export {
  snakeRef ,
  foodRef ,
  canvas ,
}
/* snakeRef Not a pure module */
